services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
      target: downloader
    volumes:
      - ./hashes:/app/hashes
    command: ["python3", "main.py"]
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: service
    volumes:
      - ./hashes:/app/hashes
    ports:
      - "5001:5001"
    depends_on:
      - downloader
    restart: unless-stopped
